### ISSUE TITLE
Convert frontend to TS

### ISSUE THREAD

**Issue by monkeytypegeorge** [Miodec/monkeytype#2431]
- [x] Setup compilation (@sondrekje) (#2464)
 - [x] Account (@Ferotiq) (#2494)
 - [x] Controllers (@Miodec, @DanGonite57)
 - [x] Elements (@Miodec)
 - [x] Observables (@Miodec)
 - [x] Pages (@Miodec)
 - [x] Popups (@Miodec)
 - [x] Settings (@rizwanmustafa, @Miodec) (#2499) (#2509)
 - [x] States
 - [x] Test (@Ferotiq, @Miodec) (#2540) (#2601)
 - [x] Root files (@Ferotiq, @Miodec) (#2539)

To allow multiple contributors to work on this, please only work on 1 task at a time.

**Comment by Miodec** [comment]
# On hold by #2462

**Comment by rizwanmustafa** [comment]
I want to work on settings.

**Comment by Ferotiq** [comment]
Finally done

**Comment by Miodec** [comment]
![ablobblewobble-blob](https://user-images.githubusercontent.com/13181393/160007299-32077ea2-3c86-4aae-9359-1f3c55a11470.gif)
